---
title: "Trabajos prácticos anteriores"
description: |
  
---


Para las ediciones anteriores de los Trabajos Prácticos, se ha creado un repositorio público en GitHub, vinculándolo a un proyecto desde RStudio. En estos, se desarrolló un RScript en donde se trabajó una base de datos del último relevamiento nacional de barrios populares (RENABAP). 

En primera instancia, se respondieron las siguientes preguntas: ¿Cuántos barrios populares se encuentran en el Área Metropolitana de Buenos Aires y, en promedio, cuántas viviendas y familias contienen? ¿Cuáles son los 10 departamentos con mayor cantidad de barrios populares? ¿Cuál es el departamento con mayor cantidad de viviendas y familias? 

En segundo lugar, se visualizaron en gráficos y mapas estos resultados, a fin de observar la distribución espacial de los de los barrios populares, así como la cantidad de hogares y familias. Asimismo, se incorporaron otras visualizaciones relativas al acceso a servicios básicos (energía, efluentes cloacales, agua), a fin de identificar patrones espaciales de mayor vulnerabilidad. 

  

- **Trabajo Práctico I**  
https://github.com/milliebarchi/IAU_II_TP1.git  

- **Trabajo Práctico II**  
https://github.com/milliebarchi/IAU_II_TP2.git